### ISSUE TITLE
Conditional Rendering on Views

### ISSUE THREAD

**Issue by jmanacup** [samassango/react-native-multi-steps#1]
Good day!

Was trying out the Multistep function and was just wondering if it is possible to do conditional rendering on the views. I am creating an app where questions depend on the previous answer and I tried doing,

`                    <View>
                        {false && (
                            <>
                                <Text>
                                    Piedmont, or mountain, glaciers are found in
                                    many parts of the world. In North America...
                                </Text>
                            </>
                        )}`

but it just shows up an empty screen with the buttons. Is there a way where the next section will transition to the section after it?

Thanks!

**Comment by samassango** [comment]
Good day @jmanacup 

Thanking for reporting the condition rendering issue, it's now resolved on the new version of ``react-native-multisteps`` version `0.1.6`. 

Thank you once again
