### ISSUE TITLE
Next Button Initial Placement

### ISSUE THREAD

**Issue by jmanacup** [samassango/react-native-multi-steps#2]
Good day!

I was just wondering if it is possible for the next button at the start of view can be placed in the right side of the view? (Default is currently in the left side). It can be a new PropType under the config prop. I feel like it would be more natural for the next button to be on the right side just like its placement when "previous" and "next" button are visible.

**Comment by samassango** [comment]
Good day!
I will consider making those changes, so the next button will be on the right by default. Even though to achieve the same results you can use the ``containerButtonStyle`` property example `` containerButtonStyle={{
          display: 'flex',
          flexDirection: 'row',
          justifyContent: 'flex-end',
          paddingLeft: 10,
          paddingRight: 30,
        }}``
This style will move the next button to the right.

Thanks

**Comment by samassango** [comment]
Good day!

I have release version ``0.1.7`` which come with the next button aligned right by default.

Thanks
